import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export async function getStaticProps() {
  const params = {
    expression: 'folder="image-upload"'
  }
  const paramString = Object.keys(params).map(key => `${key}=${encodeURIComponent(params[key])}`).join('&');

  const results = await fetch(`https://api.cloudinary.com/v1_1/${process.env.NEXT_PUBLIC_CLOUDNAME}/resources/search?${paramString}`, {
    headers: {
      Authorization: `Basic ${Buffer.from(process.env.CLOUDINARY_API_KEY + ':' + process.env.CLOUDINARY_API_SECRET).toString('base64')}`
    },
  }).then(r => r.json());
  console.log('results', results);

  const { resources } = results;

  const images = resources.map(resource => {
    const { width, height } = resource;
    return {
      id: resource.asset_id,
      title: resource.public_id,
      file: resource.secure_url,
      width,
      height,
    }
  });
  return {
    props: {
      images
    }
  }
}

export default function Home({images}) {
  return (
    <>
      <Head>
        <title>Image Gallery</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>GALLERY</h1>
        <ul className={styles.imgList}>
          {images.map((image) => (
          <li key={image.id}>
            <div className={styles.imgContainer}>
              <Image
              src={image.file}
	            alt=""
	            width="350"
              height="350"
              className={styles.images}
              />
            </div>
          </li>
          )
          )
          }
        </ul>
      </main>
    </>
  )
}
